server:
  port: 8080

spring:
  application:
    name: WebTaskManagementApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/task_master_db
    username: postgres
    password: 1543

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update